<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="3" ignored="0" total="8" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Master Suite" duration-ms="0" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
    <groups>
    </groups>
  </suite> <!-- Master Suite -->
  <suite name="Regression Suite" duration-ms="64" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
    <groups>
    </groups>
    <test name="Regression Login Test" duration-ms="37" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
      <class name="regression.TestCase1">
        <test-method status="PASS" signature="creatingDBConnection()[pri:0, instance:regression.TestCase1@42d80b78]" name="creatingDBConnection" is-config="true" duration-ms="2" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatingDBConnection -->
        <test-method status="PASS" signature="lunchBrowser()[pri:0, instance:regression.TestCase1@42d80b78]" name="lunchBrowser" is-config="true" duration-ms="1" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchBrowser -->
        <test-method status="PASS" signature="doUserReg()[pri:1, instance:regression.TestCase1@42d80b78]" name="doUserReg" duration-ms="4" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:regression.TestCase1@42d80b78]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="lunchBrowser()[pri:0, instance:regression.TestCase1@42d80b78]" name="lunchBrowser" is-config="true" duration-ms="1" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:2, instance:regression.TestCase1@42d80b78]" name="doLogin" duration-ms="3" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:regression.TestCase1@42d80b78]" name="closeBrowser" is-config="true" duration-ms="0" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="closingDBConnection()[pri:0, instance:regression.TestCase1@42d80b78]" name="closingDBConnection" is-config="true" duration-ms="1" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingDBConnection -->
      </class> <!-- regression.TestCase1 -->
    </test> <!-- Regression Login Test -->
    <test name="Regression Validation Test" duration-ms="13" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
      <class name="regression.TestCase2">
        <test-method status="FAIL" signature="validateTitles()[pri:0, instance:regression.TestCase2@7cd62f43]" name="validateTitles" duration-ms="7" started-at="2020-05-11T11:23:46Z" finished-at="2020-05-11T11:23:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Gmail.com expected:<Yahoo.com> but was:<Title not matching>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Gmail.com expected:<Yahoo.com> but was:<Title not matching>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at regression.TestCase2.validateTitles(TestCase2.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- regression.TestCase2 -->
    </test> <!-- Regression Validation Test -->
  </suite> <!-- Regression Suite -->
  <suite name="Functional Suite" duration-ms="267" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
    <groups>
    </groups>
    <test name="Login Test" duration-ms="120" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
      <class name="testCases.TestCase1">
        <test-method status="PASS" signature="creatingDBConnection()[pri:0, instance:testCases.TestCase1@d2cc05a]" name="creatingDBConnection" is-config="true" duration-ms="29" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatingDBConnection -->
        <test-method status="PASS" signature="doUserReg()[pri:1, instance:testCases.TestCase1@d2cc05a]" name="doUserReg" duration-ms="14" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="PASS" signature="lunchBrowser()[pri:0, instance:testCases.TestCase1@d2cc05a]" name="lunchBrowser" is-config="true" duration-ms="0" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchBrowser -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testCases.TestCase1@d2cc05a]" name="closeBrowser" is-config="true" duration-ms="5" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="doLogin()[pri:2, instance:testCases.TestCase1@d2cc05a]" name="doLogin" duration-ms="4" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="lunchBrowser()[pri:0, instance:testCases.TestCase1@d2cc05a]" name="lunchBrowser" is-config="true" duration-ms="0" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchBrowser -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testCases.TestCase1@d2cc05a]" name="closeBrowser" is-config="true" duration-ms="0" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="closingDBConnection()[pri:0, instance:testCases.TestCase1@d2cc05a]" name="closingDBConnection" is-config="true" duration-ms="1" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingDBConnection -->
      </class> <!-- testCases.TestCase1 -->
    </test> <!-- Login Test -->
    <test name="ValidateTitle Test" duration-ms="18" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
      <class name="testCases.TestCase2">
        <test-method status="FAIL" signature="validateTitles()[pri:0, instance:testCases.TestCase2@523884b2]" name="validateTitles" duration-ms="0" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title not matching expected [Yahoo.com] but found [Gmail.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title not matching expected [Yahoo.com] but found [Gmail.com]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at testCases.TestCase2.validateTitles(TestCase2.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- testCases.TestCase2 -->
    </test> <!-- ValidateTitle Test -->
    <test name="Dependency Test" duration-ms="25" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
      <class name="testCases.TestCase3">
        <test-method status="FAIL" signature="doUserRegistration()[pri:1, instance:testCases.TestCase3@68c4039c]" name="doUserRegistration" duration-ms="6" started-at="2020-05-11T11:23:45Z" finished-at="2020-05-11T11:23:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User is not registered]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User is not registered
at org.testng.Assert.fail(Assert.java:96)
at testCases.TestCase3.doUserRegistration(TestCase3.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserRegistration -->
        <test-method status="SKIP" signature="doLogin()[pri:2, instance:testCases.TestCase3@68c4039c]" name="doLogin" duration-ms="0" started-at="2020-05-11T11:23:45Z" depends-on-methods="testCases.TestCase3.doUserRegistration" finished-at="2020-05-11T11:23:45Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.doLogin()[pri:2, instance:testCases.TestCase3@68c4039c] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.doLogin()[pri:2, instance:testCases.TestCase3@68c4039c] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
      </class> <!-- testCases.TestCase3 -->
    </test> <!-- Dependency Test -->
  </suite> <!-- Functional Suite -->
</testng-results>
